# This file created by ruzhu chen to build conda package from prebuilt wheel file
# for Power9 running Python 3.7
# ------------------------------------------------
package:
    name: pyarrow
    version: 0.15.1
build:
    number: '2'
    string: py37ppc64le_gpu
requirements:
    build:
      - python 3.7
      - numpy
      - pip
    run: 
      - python
      - numpy
      - libutf8proc
      - libprotobuf=3.11
      - libboost=1.73
      - bzip2
      - lz4
      - brotli
      - six
      - glog
      - orc=1.6.5
test:
  imports:
    - pyarrow
about:
    home: http://github.com/apache/arrow
    license: Apache-2.0
    summary: Python libraries for Apache Arrow
